steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/droneapiserver:$SHORT_SHA', '.']
  dir: 'APIServer'
images: ['eu.gcr.io/$PROJECT_ID/droneapiserver:$SHORT_SHA']
