steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'eu.gcr.io/lunar-standard-157209/droneapiserver:3.0.9']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/lunar-standard-157209/droneapiserver:3.0.9', '.']
  dir: 'APIServer'
images: ['eu.gcr.io/lunar-standard-157209/droneapiserver:3.0.9']
