apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-cluster-eu-default-pool-4d580016-p7lp
    fsType: ext4

