###################################################################
# droneapiworker stateful container deployment
###################################################################
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: droneapiworker
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: droneapiworker
  serviceName: "droneapiworker"
  replicas: 1
  template:
    metadata:
      labels:
        app: droneapiworker
        tier: backend
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: droneapiworker
        image: lesterthomas/droneapiworker:3.0.10
        env:
        - name: DRONEAPI_URL
          value: http://droneapi.ddns.net
        - name: DOCKER_DRONESIM_IMAGE
          value: lesterthomas/dronesim:1.8
        ports:
        - containerPort: 1236
          name: droneapiworker
        livenessProbe:
          httpGet:
            path: /admin
            port: 1236