apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: droneapiworker
spec:
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: droneapiworker # has to match .spec.template.metadata.labels
  serviceName: "droneapiworker"
  replicas: 2
  template:
    metadata:
      labels:
        app: droneapiworker # has to match .spec.selector.matchLabels
        tier: backend
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: droneapiworker
        image: lesterthomas/droneapiworker:3.0.6
        env:
        - name: DRONEAPI_URL
          value: http://test.droneapi.net
        - name: DOCKER_DRONESIM_IMAGE
          value: lesterthomas/dronesim:1.8
        ports:
        - containerPort: 1236
          name: droneapiworker
